site_name: Chrysalis
# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    # Default values, taken from mkdocs_theme.yml
  language: en
    # - navigation.instant
  # palette:
  #   scheme: chryscloudcolor
  #   primary: indigo
  #   accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon-black.png
  logo: assets/favicon.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chryscloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChrysCloud
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chryscloud/

extra_css:
  - stylesheets/extra.css


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Chrysalis Edge:
    - About: edge-proxy/homepage.md
    - Getting Started:
        - Before you begin: edge-proxy/getting-started/prerequisites.md
        - Quick Start: edge-proxy/getting-started/quick-start.md
        - Connect RTSP Camera: edge-proxy/getting-started/portal-usage.md
        - Docker Playbook: edge-proxy/getting-started/docker-playbook.md
    - Examples:
        - Prerequisites: edge-proxy/examples/prerequsities.md
        - List Cameras: edge-proxy/examples/basic-usage.md
        - Display Video: edge-proxy/examples/display.md
        - Video Probe: edge-proxy/examples/probe.md
    - Custom configuration:
        - Custom Chrysalis configuration: edge-proxy/custom-configuration/chrysalis-config.md
        - Custom redis configuration: edge-proxy/custom-configuration/redis-config.md
    - Building from Source: 
        - Building from Source: edge-proxy/build-from-source/bfs.md
    - Video API:
        - Overview: edge-proxy/grpc/prerequisites.md
    - REST Process API:
        - REST API: edge-proxy/apis/rest_api_curl.md


        # - Python Examples: edge-proxy/examples/python-examples.md
        # - OpenCV Display: edge-proxy/examples/display.md
        # - Storage: edge-proxy/examples/storage-onoff.md
