site_name: Chrysalis Cloud
# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    # Default values, taken from mkdocs_theme.yml
  language: en
    # - navigation.instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon-black.png
  logo: assets/favicon.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chryscloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ChrysCloud
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/chryscloud/


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Features: features.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Quick Start: getting-started/quick-start.md
      - Portal Usage: getting-started/portal-usage.md
  - Custom configuration:
      - Custom redis configuration: custom-configuration/redis-config.md
      - Custom Chrysalis configuration: custom-configuration/chrysalis-config.md
  - Building from Source: 
      - Building from Source: build-from-source/bfs.md
  - Examples:
      - Prerequisites: examples/prerequisites.md
      - Basic Usage: examples/basic-usage.md
      - OpenCV Display: examples/display.md
      - Storage: examples/storage-onoff.md
  - API References:
      - REST API: apis/rest_api.md
